### ISSUE TITLE
Pypi version of crewai-tools is truncated

### ISSUE THREAD

**Issue by geverit4** [joaomdmoura/crewAI-tools#20]
It looks like crewai-tools is corrupt on the pypi site.  

`pip install crewai-tools `

does not install the "add" method on in embedchain_adapter.py.

Installing directly from github solves the problem:

pip install git+https://github.com/joaomdmoura/crewAI-tools.git

**Comment by joaomdmoura** [comment]
should be fixed now 😄  good catch
