### ISSUE TITLE
Possible redudant code

### ISSUE THREAD

**Issue by Zyzzx** [joaomdmoura/crewAI-tools#26]
https://github.com/joaomdmoura/crewAI-tools/blob/9181d05c4c8bd8771bf01fb74ada5ca3f687c37e/crewai_tools/tools/selenium_scraping_tool/selenium_scraping_tool.py#L58-L60

The function is called without iterating before it is called again and iterated upon. Not sure if there is are reason to have such a redundant pattern. It doesn't break anything, but it is odd.

**Comment by joaomdmoura** [comment]
Good catch, probably a TYPO, fixing it
