### ISSUE TITLE
Is it possible to specify a tool inside of src/crew_name/config/agents.yaml?

### ISSUE THREAD

**Issue by ChaseKolozsy** [joaomdmoura/crewAI-tools#27]
``object_researcher:
  role: >
    Attribute Researcher
  goal: >
    Gather all of the attributes of an object for the purpose of generating a profile:
      - components
      - states 
      - direct actions it can perform
      - indirect actions that can be perfomed on it, with it, to it, etc
      - immutable attributes
      - mutable attributes
  backstory: >
    An erudite and meticulous researcher, who spends all day and night thinking about the nature of objects.
  allow_delegation: false
  verbose: true
  tools: 
    - search_tool

**Comment by joaomdmoura** [comment]
No, the idea is that that piece would be inside the actual agent definition, and the yml file would be more for the prompted related pieces, but we could make it work if it's valuable, would love to know more about the use case

**Comment by ChaseKolozsy** [comment]
That's good to know. I thought it might be useful to just have a complete profile of the agent in yaml that one could easily refer to as a spec sheet for the agent instead of it being separated by multiple files. If it doesn't hurt anything, then perhaps it might be useful to add the field to the yaml anyway.
