### ISSUE TITLE
GithubSearchTool in Agent / Task configuration

### ISSUE THREAD

**Issue by mt-ghub** [joaomdmoura/crewAI-tools#30]
Has anyone got an example of how to use this tool in an agent / task setup? eg how do I tell the LLM to search a specific repo, using a specific github token?

I see in the tool Readme.md an example, but, the LLM I am using mostly ignores the repo and token.

I'm new to CrewAI and would really appreciate it if someone has a working example of how this could be used.

Thanks

**Comment by windowshopr** [comment]
```
frontend_developer.tools.append(GithubSearchTool(gh_token=GITHUB_API_KEY, content_types=['code', 'repo'], github_repo="sveltejs/svelte"))
```

I found to make sure you don't have "https://github.com/" in the `github_repo` parameter, just the ower and repo name part of the link.

**Comment by joaomdmoura** [comment]
sorry we will add this to docs as we are building new ones
